apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: crm-app
  name: crm-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: crm-app
  type: NodePort
status:
  loadBalancer: {}
